[package]
name = "name-lookup"
version = "0.1.0"
edition = "2021"

[dependencies]
bloom-filter-yss = { path = "../bloom_filter" }
dotenvy = "0.15.7"
sqlx = { version = "0.8", features = ["runtime-tokio", "postgres"] }
tokio = { version = "1.43.0", features = ["full"] }
